name: CI

on:
  workflow_dispatch:

  release:
    # this runs CI only when a release is created at first (and not when it is
    # edited or published)
    types: [created]

  push:
    branches: portable

  pull_request:
    branches: portable

jobs:
  build:
    name: Build WASM Postgres
    runs-on: ubuntu-latest
    env:
      WASI_SDK_VERSION: 24.0.5
      WASI_SDK_ARCHIVE: python3.13-wasi-sdk-Ubuntu-22.04.tar.lz4
      DEBUG: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install python-wasi-sdk for wasi+prebuilts
        working-directory: /
        run: |
          sudo apt-get install -y lz4 wget pv bash
          sudo rm $(which node) $(which npm)
          echo https://github.com/pygame-web/python-wasi-sdk/releases/download/$WASI_SDK_VERSION/$WASI_SDK_ARCHIVE
          curl -sL --retry 5 https://github.com/pygame-web/python-wasi-sdk/releases/download/$WASI_SDK_VERSION/$WASI_SDK_ARCHIVE | tar xvP --use-compress-program=lz4 | pv -p -l -s 23000 >/dev/null

#      - name: Build postgres WASM via poswasi-sdk
#        run: |
#          NO_SDK_CHECK=true WASI=true contrib=false extra=false bash ./cibuild.sh contrib extra node linkweb pglite

      - name: Build postgres WASM via portable-emsdk
        run: |
          bash ./ci-16_6_WASM.sh

#      - name : "Upload to GitHub pages"
#        uses: JamesIves/github-pages-deploy-action@v4.4.1
#        with:
#          branch: gh-pages
#          folder: /tmp/fs/tmp/web

      - name: Test pglite
        run: |
           echo test skipped
#          bash ./cibuild.sh pglite-test

